env:
  PREVIEW_ENV_FRONTEND_DOMAIN: pr-${{ github.event.number }}.preview.${{ secrets.DOMAIN_PRODUCTION }}

jobs:
  clean-preview-env:
    runs-on: ubuntu-latest
    steps:
      - env:
          CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        id: delete_record
        name: Delete preview env's DNS Record
        uses: marcelofcandido/yet-another-cloudflare-action@v1
        with:
          delete: true
          record: ${{ env.PREVIEW_ENV_FRONTEND_DOMAIN }}
          zone_name: ${{ secrets.CLOUDFLARE_ZONE_NAME }}
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - env:
          PORTER_CLUSTER: "5703"
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PROJECT: "13871"
          PORTER_TOKEN: ${{ secrets.PORTER_APP_13871_5703 }}
        name: Delete preview environment
        run: porter target delete --name ${{ github.event.pull_request.head.ref }} --force
        timeout-minutes: 30

name: Clean Preview Environment resources

on:
  pull_request:
    types: [closed]
