jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: vars
        name: Set Github tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Porter Replace Action
        uses: porter-dev/replace-action@v0.1.0
        with:
          file_path: ./frontend/frontend.porter.yaml
          key_values: $$DOMAIN_NAME=${{ secrets.DOMAIN_FOR_PRODUCTION_DEPLOYMENT }}
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - env:
          DOCKER_BUILDKIT: "1"
          PORTER_APP_NAME: pylon-proxy-frontend
          PORTER_CLUSTER: "4359"
          PORTER_DEPLOYMENT_TARGET_ID: ce4ad44b-b230-4232-82b8-4f15d31320b2
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PROJECT: "13871"
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_13871_4359 }}
        name: Deploy stack
        run: exec porter apply -f ./frontend/frontend.porter.yaml
        timeout-minutes: 30
name: Deploy to pylon-proxy-frontend
"on":
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - "backend/**"
